Add 'extras' field when getting allocations
ChameleonCloud/blazar pull request #45
Opened 2021-08-06 21:35 UTC by Mark-Powers

This field is a list of extra information to include with allocations
so they can be used by the calendar. This should probably be configured
by the config file, or something.

Initially, the only extra is `Reserved by` which is associated with the name
of the user who created the allocation.

2021-08-13 23:02 UTC, diurnalist requested changes
Looking good, I'm a bit concerned about the additional performance hit, and maybe we can have a more flexible solution by putting this as a GET param.

2021-08-13 23:02 UTC, diurnalist commented on blazar/plugins/base.py
> +                        (_("Reserved by"), lease_to_name[alloc["lease_id"]]),
I think it's better to return machine_names on endpoints like this. Horizon can be in charge of translating them to some proper UI text; as a GUI, this is its responsibility. Blazar shouldn't be making too many decisions about how data is displayed.

2021-08-13 23:02 UTC, diurnalist commented on blazar/plugins/devices/device_plugin.py
> +        self.add_extra_allocation_info(devices_allocations)
Just wondering, what if `extras` was a GET parameters? That might be more flexible. In this arrangement, an interesting config value would be to support disabling some extra fields from being requested? Maybe a future enhancement. We don't currently have anything sensitive in Blazar.

2021-08-23 21:38 UTC, Mark-Powers commented
Keystone does have a way to get all users, which is now used.

2021-08-26 17:13 UTC, diurnalist approved these changes
Nice, this should be much faster now :)

2021-09-01 19:20 UTC, merged