Allow reallocate to limit scope to a single lease for non-admin users
ChameleonCloud/blazar pull request #77
Opened 2022-06-10 00:02 UTC by super-cooper

Non-admin users are now allowed to use the `host-reallocate` command on leases they own. The command will only be allowed if `--lease-id <lease-id>` is supplied, and the lease is one they own.

2022-06-10 00:02 UTC, super-cooper commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow reallocate to limit scope to a single lease](https://trello.com/c/4sDLPBYq/2685-allow-reallocate-to-limit-scope-to-a-single-lease)

2022-06-10 14:16 UTC, Mark-Powers requested changes
Looks good, but a few things to address before going forward. @diurnalist may want to comment on the new policy change.

2022-06-10 14:16 UTC, Mark-Powers commented on blazar/plugins/oshosts/host_plugin.py
> +    @policy.authorize('oshosts', 'put')
Is this left in from testing something? This method is operating on the lease, and the [lease policy](https://github.com/ChameleonCloud/blazar/blob/chameleoncloud/train/blazar/api/v1/leases/service.py#L68) is checked before it is called.

2022-06-10 14:16 UTC, Mark-Powers commented on blazar/plugins/oshosts/host_plugin.py
> +            policy.check_enforcement('leases', action='put', ctx=ctx, target={
I think we actually need to also check a new policy here (`reallocate_lease` or something) in case an operator wants to prevent users from reallocating their own leases.

2022-06-10 14:19 UTC, super-cooper commented on blazar/plugins/oshosts/host_plugin.py
> +    @policy.authorize('oshosts', 'put')
I genuinely do not know how this ended up here.

2022-06-13 18:36 UTC, super-cooper commented
Tested, and works

2022-06-13 18:37 UTC, Mark-Powers approved these changes
🚢  Thanks for testing it!

2022-06-13 18:53 UTC, merged